service: health-planet-client-backend
frameworkVersion: '3'
configValidationMode: error
useDotenv: true
deprecationNotificationMode: warn:summary

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ap-northeast-1
  profile: hobby
  stackName: health-planet-client-backend
  tags:
    service: health-planet-client
  deploymentMethod: direct
  runtime: nodejs16.x

  tracing:
    apiGateway: true
    lambda: true

custom:
  functionsBasePath: ./dist/
  serverless-layers:
    layersDeploymentBucket: d-hori-health-planet-client-prod-layers

functions:
  backend:
    handler: handler.main
    runtime: nodejs16.x
    memorySize: 512
    timeout: 3
#    environment:
#      FOO: BAR
    name: health-planet-client-${sls:stage}-lambda
    description: API backend
    events:
      - http:
          path: /auth
          method: GET
      - http:
          path: /token
          method: POST
      - http:
          path: /status/innerscan.json
          method: GET

plugins:
  - serverless-functions-base-path
  - serverless-offline
  - serverless-layers
  - serverless-dotenv-plugin
